name: flutter_nft
description: A universal Flutter library for NFT operations across multiple blockchains
version: 1.3.0
homepage: https://github.com/libsFlutter/flutter_nft

environment:
  sdk: '^3.9.0'
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_yuku: ^1.0.0
  web3dart: ^3.0.0
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  crypto: ^3.0.3
  http: ^1.1.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.4.2
  build_runner: ^2.7.1
  json_serializable: ^6.11.1

flutter: