name: flutter_nft
description: A universal Flutter library for NFT operations across multiple blockchains
version: 1.3.0
homepage: https://github.com/libsFlutter/flutter_nft

environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_yuku:
    path: ../flutter_yuku
  web3dart: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.4.2
  build_runner: ^2.7.1
  json_serializable: ^6.11.1

flutter: