name: flutter_nft
description: A universal Flutter library for NFT operations across multiple blockchains - provides EVM-compatible blockchain providers
version: 2.2.1
homepage: https://github.com/libsFlutter/flutter_nft

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_yuku: ^2.0.3
  web3dart: ^3.0.1
  crypto: ^3.0.3
  http: ^1.1.2
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  mockito: ^5.4.4
  build_runner: ^2.4.7

dependency_overrides:
  flutter_yuku:
    path: ../flutter_yuku

flutter: